// Code generated by valuegenerator. DO NOT EDIT

package value

import "strconv"

// Bool implements the value interface for the bool type
type Bool bool

// Type returns the underlying type of the value as a string
func (b *Bool) Type() string {
	return "bool"
}

// Get returns the underlying value as an interface{}
func (b *Bool) Get() interface{} {
	return bool(*b)
}

// Set a value from a string
func (b *Bool) Set(val string) error {
	pv, err := strconv.ParseBool(val)
	if err == nil {
		*b = Bool(pv)
	}
	return err
}

// String returns the value as a string
func (b *Bool) String() string {
	return strconv.FormatBool(bool(*b))
}

// Clone duplicates the Bool as a copy of the instance
func (b *Bool) Clone() Value {
	ptr := new(Bool)
	*ptr = *b
	return ptr
}

// Zero returns the zero value of the underlying primitive
func (b *Bool) Zero() interface{} {
	ptr := new(bool)
	return *ptr
}

// BindBool returns a new Bool with the underlying bool used for state.
func BindBool(b *bool) *Bool {
	return (*Bool)(b)
}
