// Code generated by valuegenerator. DO NOT EDIT

package value

var testBoolGetTestData = []TestBoolGetTest{
	{
		name: "basic",
		a:    ptrToBool(true),
		want: true,
	},
}

var testBoolSetTestData = []TestBoolSetTest{
	{
		name:    "basic",
		s:       "true",
		a:       ptrToBool(true),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testBoolStringTestData = []TestBoolStringTest{
	{
		name: "basic",
		a:    ptrToBool(true),
		want: "true",
	},
}

var testBindBoolTestData = []TestBindBoolTest{
	{
		name: "basic",
		x:    boolPtr(true),
		want: ptrToBool(true),
	},
}
