// Code generated by valuegenerator. DO NOT EDIT

package value

var testByteGetTestData = []TestByteGetTest{
	{
		name: "basic",
		a:    ptrToByte('a'),
		want: byte('a'),
	},
}

var testByteSetTestData = []TestByteSetTest{
	{
		name:    "basic",
		s:       "a",
		a:       ptrToByte('a'),
		wantErr: false,
	},
	{
		name:    "multi-chars",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
	{
		name:    "null",
		s:       "",
		a:       nil,
		wantErr: true,
	},
}

var testByteStringTestData = []TestByteStringTest{
	{
		name: "basic",
		a:    ptrToByte('a'),
		want: "a",
	},
}

var testBindByteTestData = []TestBindByteTest{
	{
		name: "basic",
		x:    bytePtr('a'),
		want: ptrToByte('a'),
	},
}
