#!/bin/bash
set -e

go fmt ./...
golint -set_exit_status ./...
go vet ./...
errcheck -ignoretests ./...
staticcheck ./...
gosec -quiet ./...

go test ./... -cover -coverprofile=coverage.out -v
go tool cover -html coverage.out -o coverage.html
go tool cover -func coverage.out
