// Code generated by valuegenerator. DO NOT EDIT

package value

var testComplex64GetTestData = []TestComplex64GetTest{
	{
		name: "basic",
		a:    ptrToComplex64(complex(float32(7), float32(7))),
		want: complex(float32(7), float32(7)),
	},
}

var testComplex64SetTestData = []TestComplex64SetTest{
	{
		name:    "basic",
		s:       "7+7i",
		a:       ptrToComplex64(complex(float32(7), float32(7))),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
	{
		name:    "not complex",
		s:       "7",
		a:       nil,
		wantErr: true,
	},
}

var testComplex64StringTestData = []TestComplex64StringTest{
	{
		name: "basic",
		a:    ptrToComplex64(complex(float32(7), float32(7))),
		want: "7+7i",
	},
}

var testBindComplex64TestData = []TestBindComplex64Test{
	{
		name: "basic",
		x:    complex64Ptr(complex(7, 7)),
		want: ptrToComplex64(complex(7, 7)),
	},
}
