// Code generated by valuegenerator. DO NOT EDIT

package value

var testComplex128GetTestData = []TestComplex128GetTest{
	{
		name: "basic",
		a:    ptrToComplex128(complex(7, 7)),
		want: complex(7, 7),
	},
}

var testComplex128SetTestData = []TestComplex128SetTest{
	{
		name:    "basic",
		s:       "7+7i",
		a:       ptrToComplex128(complex(7, 7)),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
	{
		name:    "not complex",
		s:       "7",
		a:       nil,
		wantErr: true,
	},
}

var testComplex128StringTestData = []TestComplex128StringTest{
	{
		name: "basic",
		a:    ptrToComplex128(complex(7, 7)),
		want: "7+7i",
	},
}

var testBindComplex128TestData = []TestBindComplex128Test{
	{
		name: "basic",
		x:    complex128Ptr(complex(7, 7)),
		want: ptrToComplex128(complex(7, 7)),
	},
}
