// Code generated by valuegenerator. DO NOT EDIT

package value

import "time"

var testDurationGetTestData = []TestDurationGetTest{
	{
		name: "basic",
		a:    ptrToDuration(7 * time.Second),
		want: time.Duration(7_000_000_000),
	},
}

var testDurationSetTestData = []TestDurationSetTest{
	{
		name:    "basic",
		s:       "7s",
		a:       ptrToDuration(7 * time.Second),
		wantErr: false,
	},
}

var testDurationStringTestData = []TestDurationStringTest{
	{
		name: "basic",
		a:    ptrToDuration(7 * time.Second),
		want: "7s",
	},
}

var testBindDurationTestData = []TestBindDurationTest{
	{
		name: "basic",
		x:    durationPtr(7 * time.Second),
		want: ptrToDuration(7 * time.Second),
	},
}
