// Code generated by valuegenerator. DO NOT EDIT

package value

var testInt32GetTestData = []TestInt32GetTest{
	{
		name: "basic",
		a:    ptrToInt32(7),
		want: int32(7),
	},
}

var testInt32SetTestData = []TestInt32SetTest{
	{
		name:    "basic",
		s:       "7",
		a:       ptrToInt32(7),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testInt32StringTestData = []TestInt32StringTest{
	{
		name: "basic",
		a:    ptrToInt32(7),
		want: "7",
	},
}

var testBindInt32TestData = []TestBindInt32Test{
	{
		name: "basic",
		x:    int32Ptr(7),
		want: ptrToInt32(7),
	},
}
