// Code generated by valuegenerator. DO NOT EDIT

package value

var testInt64GetTestData = []TestInt64GetTest{
	{
		name: "basic",
		a:    ptrToInt64(7),
		want: int64(7),
	},
}

var testInt64SetTestData = []TestInt64SetTest{
	{
		name:    "basic",
		s:       "7",
		a:       ptrToInt64(7),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testInt64StringTestData = []TestInt64StringTest{
	{
		name: "basic",
		a:    ptrToInt64(7),
		want: "7",
	},
}

var testBindInt64TestData = []TestBindInt64Test{
	{
		name: "basic",
		x:    int64Ptr(7),
		want: ptrToInt64(7),
	},
}
