// Code generated by valuegenerator. DO NOT EDIT

package value

var testInt8GetTestData = []TestInt8GetTest{
	{
		name: "basic",
		a:    ptrToInt8(7),
		want: int8(7),
	},
}

var testInt8SetTestData = []TestInt8SetTest{
	{
		name:    "basic",
		s:       "7",
		a:       ptrToInt8(7),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testInt8StringTestData = []TestInt8StringTest{
	{
		name: "basic",
		a:    ptrToInt8(7),
		want: "7",
	},
}

var testBindInt8TestData = []TestBindInt8Test{
	{
		name: "basic",
		x:    int8Ptr(7),
		want: ptrToInt8(7),
	},
}
