// Code generated by valuegenerator. DO NOT EDIT

package value

var testIntGetTestData = []TestIntGetTest{
	{
		name: "basic",
		a:    ptrToInt(7),
		want: 7,
	},
}

var testIntSetTestData = []TestIntSetTest{
	{
		name:    "basic",
		s:       "7",
		a:       ptrToInt(7),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testIntStringTestData = []TestIntStringTest{
	{
		name: "basic",
		a:    ptrToInt(7),
		want: "7",
	},
}

var testBindIntTestData = []TestBindIntTest{
	{
		name: "basic",
		x:    intPtr(7),
		want: ptrToInt(7),
	},
}
