// Code generated by valuegenerator. DO NOT EDIT

package value

import "time"

var sampleText1 = "2020-01-01T02:03:04Z"
var sampleTime1 = time.Date(2020, 1, 1, 2, 3, 4, 0, time.UTC)

var testTimeGetTestData = []TestTimeGetTest{
	{
		name: "basic",
		a:    ptrToTime(sampleTime1),
		want: sampleTime1,
	},
}

var testTimeSetTestData = []TestTimeSetTest{
	{
		name:    "basic",
		s:       sampleText1,
		a:       ptrToTime(sampleTime1),
		wantErr: false,
	},
	{
		name:    "not a time",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testTimeStringTestData = []TestTimeStringTest{
	{
		name: "basic",
		a:    ptrToTime(sampleTime1),
		want: sampleText1,
	},
}

var testBindTimeTestData = []TestBindTimeTest{
	{
		name: "basic",
		x:    timePtr(sampleTime1),
		want: ptrToTime(sampleTime1),
	},
}
