// Code generated by valuegenerator. DO NOT EDIT

package value

var testUint64GetTestData = []TestUint64GetTest{
	{
		name: "basic",
		a:    ptrToUint64(7),
		want: uint64(7),
	},
}

var testUint64SetTestData = []TestUint64SetTest{
	{
		name:    "basic",
		s:       "7",
		a:       ptrToUint64(7),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testUint64StringTestData = []TestUint64StringTest{
	{
		name: "basic",
		a:    ptrToUint64(7),
		want: "7",
	},
}

var testBindUint64TestData = []TestBindUint64Test{
	{
		name: "basic",
		x:    uint64Ptr(7),
		want: ptrToUint64(7),
	},
}
