// Code generated by valuegenerator. DO NOT EDIT

package value

var testUint16GetTestData = []TestUint16GetTest{
	{
		name: "basic",
		a:    ptrToUint16(7),
		want: uint16(7),
	},
}

var testUint16SetTestData = []TestUint16SetTest{
	{
		name:    "basic",
		s:       "7",
		a:       ptrToUint16(7),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testUint16StringTestData = []TestUint16StringTest{
	{
		name: "basic",
		a:    ptrToUint16(7),
		want: "7",
	},
}

var testBindUint16TestData = []TestBindUint16Test{
	{
		name: "basic",
		x:    uint16Ptr(7),
		want: ptrToUint16(7),
	},
}
