// Code generated by valuegenerator. DO NOT EDIT

package value

var testUint32GetTestData = []TestUint32GetTest{
	{
		name: "basic",
		a:    ptrToUint32(7),
		want: uint32(7),
	},
}

var testUint32SetTestData = []TestUint32SetTest{
	{
		name:    "basic",
		s:       "7",
		a:       ptrToUint32(7),
		wantErr: false,
	},
	{
		name:    "not a number",
		s:       "dooker",
		a:       nil,
		wantErr: true,
	},
}

var testUint32StringTestData = []TestUint32StringTest{
	{
		name: "basic",
		a:    ptrToUint32(7),
		want: "7",
	},
}

var testBindUint32TestData = []TestBindUint32Test{
	{
		name: "basic",
		x:    uint32Ptr(7),
		want: ptrToUint32(7),
	},
}
